version: "3.7"
volumes:
  db-data:
  testsupport-data:
  zookeeper-data:
  kafka-data:
  nginx-configuration-data:
  minio-data:

services:
  eets-testcontainer-proxy:
    container_name: eets-testcontainer-proxy
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/var/eets/test/proxy-conf/cert
    depends_on:
      - "eets-testcontainer-provider-interface-service"

  eets-testcontainer-zookeeper:
    container_name: eets-testcontainer-zookeeper
    image: bitnami/zookeeper:3.8
    volumes:
      - "zookeeper-data:/bitnami/zookeeper"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.3.1
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka-data:/bitnami/kafka"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=eets-testcontainer-zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - eets-testcontainer-zookeeper

  eets-testcontainer-schema-registry:
    container_name: eets-testcontainer-schema-registry
    image: bitnami/schema-registry:7.2
    depends_on:
      - kafka
    environment:
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka:9092

  eets-testcontainer-postgres:
    image: bitnami/postgresql:11.13.0
    container_name: eets-testcontainer-postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=eets"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=db-testsupport"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eets"]
      interval: 10s
      timeout: 5s
      retries: 5

  eets-testcontainer-minio:
    image: minio/minio
    volumes:
      - minio-data:/export
    container_name: eets-testcontainer-minio
    command:
      - server
      - --address=0.0.0.0:9000
      - --console-address=0.0.0.0:9001
      - /export
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "secretsecret"
      MINIO_DEFAULT_BUCKETS: "bazg-camiuns-eets-pis-tc"

  eets-testcontainer-testsupportservice:
    image: ghcr.io/ezv-eets/eets-test-container/eets-test-support-service
    container_name: eets-testcontainer-testsupportservice
    ports:
      - "8096:8096"
    volumes:
      - ./cert/provider-signing-cert:/var/eets/test/service-conf/cert/provider-signing-cert
      - ./provider.properties:/var/eets/test/service-conf/provider.properties
    depends_on:
      - "eets-testcontainer-postgres"
      - "kafka"
      - "eets-testcontainer-schema-registry"
      - "eets-testcontainer-minio"
    environment:
      - SPRING_PROFILES_ACTIVE=testsupport
      - KAFKA_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_URL=http://kafka:9092
      - SCHEMA_REGISTRY_URL=http://eets-testcontainer-schema-registry:8081

  eets-testcontainer-provider-interface-service:
    image:  ghcr.io/ezv-eets/eets-test-container/eets-provider-interface-service
    container_name: eets-provider-interface-service
    ports:
      - "8089:8089"
    depends_on:
      - "eets-testcontainer-minio"
      - "eets-testcontainer-testsupportservice"
    environment:
      - KAFKA_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_URL=http://kafka:9092
      - SCHEMA_REGISTRY_URL=http://eets-testcontainer-schema-registry:8081
