version: "3.7"
volumes:
  db-data:
  testsupport-data:
  rabbit-data:
  nginx-configuration-data:
services:
  eets-testcontainer-proxy:
    container_name: eets-testcontainer-proxy
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/var/eets/test/proxy-conf/cert
    depends_on:
      - "eets-testcontainer-provider-interface-service"
  eets-testcontainer-messagebroker:
    image: rabbitmq:3.7.6-management
    container_name: eets-testcontainer-rabbitmq
    user: rabbitmq:rabbitmq
    volumes:
      - rabbit-data:/var/lib/rabbitmq
  eets-testcontainer-mariadb:
    image: mariadb
    container_name: eets-testcontainer-mariadb
    ports:
      - "3320:3306"
    user: mysql:mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_USER=eets
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=db-testsupport
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  eets-testcontainer-testsupportservice:
    build:
      context: ./eets-testsupport-service
      args:
        - SIGNING_CERTIFICATE_FILE=somecert.pem
    container_name: eets-testcontainer-testsupportservice
    ports:
      - "8096:8096"
    volumes:
      - ./provider.properties:/var/eets/test/service-conf/provider.properties
    depends_on:
      - "eets-testcontainer-mariadb"
      - "eets-testcontainer-messagebroker"
  eets-testcontainer-provider-interface-service:
    build: ./eets-providerinterface-service
    container_name: eets-provider-interface-service
    ports:
      - "8089:8089"
    depends_on:
      - "eets-testcontainer-testsupportservice"
