version: "3.7"
volumes:
  db-data:
  testsupport-data:
  rabbit-data:
  nginx-configuration-data:
  minio-data:
  testsupport-sig-cert-location:

services:
  eets-testcontainer-proxy:
    container_name: eets-testcontainer-proxy
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/var/eets/test/proxy-conf/cert
    depends_on:
      - "eets-testcontainer-provider-interface-service"
  eets-testcontainer-messagebroker:
    image: rabbitmq:3.7.6-management
    container_name: eets-testcontainer-rabbitmq
    user: rabbitmq:rabbitmq
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  eets-testcontainer-postgres:
    image: bitnami/postgresql:10.6.0
    container_name: eets-testcontainer-postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=eets"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=db-testsupport"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  eets-testcontainer-minio:
    image: minio/minio
    volumes:
      - minio-data:/export
    container_name: eets-testcontainer-minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "secretsecret"
    command: "server /export"
  eets-testcontainer-testsupportservice:
    image: ghcr.io/needtoroll/eets-test-container/test-support-service
    container_name: eets-testcontainer-testsupportservice
    ports:
      - "8096:8096"
    volumes:
      - ./cert/provider-signing-cert:/var/eets/test/service-conf/cert/provider-signing-cert
      - ./provider.properties:/var/eets/test/service-conf/provider.properties
    depends_on:
      - "eets-testcontainer-postgres"
      - "eets-testcontainer-messagebroker"
      - "eets-testcontainer-minio"
  eets-testcontainer-provider-interface-service:
    image: ghcr.io/needtoroll/eets-test-container/provider-interface-service
    container_name: eets-provider-interface-service
    ports:
      - "8089:8089"
    depends_on:
      - "eets-testcontainer-testsupportservice"
