version: "3.7"
volumes:
  db-data:
  testsupport-data:
  rabbit-data:
  nginx-configuration-data:
services:
  eets-testcontainer-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert/:/var/eets/test/proxy-conf/cert/
  eets-testcontainer-messagebroker:
    image: rabbitmq:3.7.6-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    environment:
      - MYSQL_USER=eets
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=db-testsupport
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  eets-testcontainer-mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  eets-testcontainer-testsupportservice:
    build: ./eets-testsupport-service
    ports:
      - "8096:8096"
    volumes:
      - testsupport-data:/var/eets/test/service-conf
  eets-provider-interface-service:
    build: ./eets-providerinterface-service
    ports:
      - "8089:8089"
