version: "3.7"
services:
  testcontainer-verification:
    image: curlimages/curl:latest
    depends_on:
      - "eets-testcontainer-provider-interface-service"
    #entrypoint: ["sh"]
    command: ["--retry-connrefused", "--retry", "10", "--retry-delay", "0","http://eets-testcontainer-testsupportservice:8096/api/testsupport/setState/SST-01a"]