name: Docker

on:
  push:
  registry_package:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
            docker compose --file docker-compose.yml --file .github/docker-compose.ci.yml build --no-cache
            docker compose --file docker-compose.yml --file .github/docker-compose.ci.yml --file .integration-test/docker-compose.test.yml run testcontainer-verification-tss
            docker compose --file docker-compose.yml --file .github/docker-compose.ci.yml --file .integration-test/docker-compose.test.yml run testcontainer-verification-pis

      - name: Dump container logs on failure
        if: failure()
        run: docker compose --file docker-compose.yml logs --no-color
